namespace AOC1._1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Day1.Task1();
            Day1.Task2();
            Day2.Task1();
            Day2.Task2();
            Day3.Task1();
            Day3.Task2();
            Day4.Task1();
            Day4.Task2();
            Day5.Task1();
            Day5.Task2();
            Day6.Task1();
            Day6.Task2();
            Day7.Task1();
            Day7.Task2();
            Day8.Task1();
            Day8.Task2();
            Day9.Task1();
            Day9.Task2();
            Day10.Task1();
            Day10.Task2();
            Day11.Task1();
            Day11.Task2();
            Day12.Task1();
            Day12.Task2();
            Day13.Task1();
            Day13.Task2();
            Day14.Task1();
            Day14.Task2();
            Day15.Task1();
            Day15.Task2();
            Day16.Task1();
            Day16.Task2();
            Day17.Task1();
            Day17.Task2();
            Day18.Task1();
            Day18.Task2();
            Day19.Task1();
            Day19.Task2();
            Day20.Task1();
            Day20.Task2();
            Day21.Task1();
            Day21.Task2();
            Day22.Task1();
            Day22.Task2();
            Day23.Task1();
            Day23.Task2();
            Day24.Task1();
            Day24.Task2();
            Day25.Task1();
            Day25.Task2();
        }
    }
}